languageCode = "en-us"
title = "Voice App Agency"
description = "We make your ideas speak"
baseURL = "http://localhost:1313"
theme = "hugo-theme-massively"

[params.posts]
    foldername = "post"
    pagesize = "6"
    featuredpost = "false"

[params.settings]
    googleanalytics = "UA-113904582-3"
    disqus = "hugo-massively"
